[build-system]
requires = [
    'hatchling',
    'hatch-vcs',
    'xtrack==0.86.1',
    'xfields==0.24.0',
    'xcoll==0.6.2',
    'xobjects==0.5.0',
    'xdeps==0.10.5',
    'xpart==0.23.0',
    'numpy<2.0',
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[project]
name = "xsuite"
authors = [
    {name = "Riccardo De Maria"},
    {name = "Giovanni Iadarola"},
    {name = "Szymon Łopaciuk"},
    {name = "et al."},
]
description = "Integrated suite for particle accelerator simulations."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
dependencies = [
    "xtrack==0.86.1",
    "xfields==0.24.0",
    "xcoll==0.6.2",
    "xobjects==0.5.0",
    "xdeps==0.10.5",
    "xpart==0.23.0",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["xsuite/"]
include = ["xsuite", "xsuite.lib"]

[project.urls]
Download = "https://pypi.python.org/pypi/xsuite"
"Bug Tracker" = "https://github.com/xsuite/xsuite/issues"
Documentation = 'https://xsuite.readthedocs.io/'
"Source Code" = "https://github.com/xsuite/xsuite"

[project.scripts]
xsuite-prebuild = "xsuite.cli:main"

[tool.hatch.build.targets.sdist]
include = [
    'xsuite/*.py',
    'xsuite/lib/*.py',
]

[tool.hatch.build.targets.wheel]
artefacts = [
    'lib/*.so',
    'lib/*.dylib',
    'lib/*.dll',
    'lib/*.json',
]

[tool.hatch.build.hooks.custom]
path = 'hatch_build.py'

[tool.cibuildwheel]
skip = [
    # PyPy does not work for us
    "pp*",
    # i686 is not needed or supported
    "*i686",
    # We don't need musl libc support
    "*musllinux*",
    # Apparently there's a problem with with Python 3.8 on ARM64 macOS; the
    # x86_64 version is run anyway pulling the x86 cffi library, building
    # x86 dylibs that cannot then be imported properly by the ARM64 Python.
    # Witnessed on here: https://github.com/pypa/cibuildwheel/issues/1278.
    # It does not make 100% sense to me, but for now this is the workaround.
    "cp38-macosx_arm64",
]
build-verbosity = 1
